USE cassavaforge;

INSERT INTO products (id, slug, name, series_code, category, application_grade, description, image_url, display_order, published) VALUES
(UUID(), 'cassava-flex-pack', 'Cassava Flex Pack', 'CF-01', 'packaging', 'Flexible packaging', 'A renewable film platform for lightweight applications where clarity and end-of-life matter.', 'assets/images/packaging.jpg', 1, 1),
(UUID(), 'cassava-clear-film', 'Cassava Clear Film', 'CF-02', 'films', 'Transparent barrier film', 'A clear, adaptable film material for thoughtful product and food-contact concepts.', 'assets/images/films.jpg', 2, 1),
(UUID(), 'cassava-molded-form', 'Cassava Molded Form', 'CF-03', 'cutlery', 'Molded products', 'A practical molded-material base for single-use products that should not outlive their purpose.', 'assets/images/cutlery.jpg', 3, 1);

INSERT INTO blog_posts (id, slug, title, category, excerpt, content, image_url, author, read_minutes, published) VALUES
(UUID(), 'why-cassava', 'Why cassava is an important material story', 'Materials', 'Cassava connects agricultural resilience with new possibilities in product design.', 'Good material choices begin with good systems thinking. Cassava grows in climates where other crops can be difficult, and its starch offers a compelling starting point for renewable material development.\n\nThe opportunity is not to replace every material overnight. It is to build credible alternatives, test them honestly, and make the better choice easier to adopt.', 'assets/images/blog-smiling-african-smallholder-cassava-farmers-standing-4.jpg', 'CassavaForge', 4, 1),
(UUID(), 'designing-for-the-next-cycle', 'Designing for the next cycle', 'Design', 'Performance and responsibility become more useful when they are considered together.', 'A material is never only a material. It is a supply chain, a manufacturing decision, a user experience, and an end-of-life question. Our work is to bring those questions into the same room early enough to make a difference.', 'assets/images/blog-minimalist-product-design-showcase-featuring-eco-5.jpg', 'CassavaForge', 3, 1),
(UUID(), 'from-farm-to-formulation', 'From farm to formulation', 'Research', 'A closer look at the material journey from cassava harvest to usable biopolymer.', 'The strongest material systems begin with a clear understanding of their feedstock. We work with agricultural partners and formulation teams to connect source quality to finished-product performance.', 'assets/images/blog-modern-biotechnology-laboratory-glassware-clear-glass-2.jpg', 'CassavaForge', 5, 1),
(UUID(), 'designing-for-compostability', 'Designing for compostability', 'Sustainability', 'End-of-life performance is a design input, not an afterthought.', 'Compostability only matters when it is designed into the full product system. That means thinking about thickness, additives, use conditions, and the environments where the material will return.', 'assets/images/blog-wide-panoramic-vista-of-a-sustainable-6.jpg', 'CassavaForge', 4, 1),
(UUID(), 'building-the-value-chain', 'Building the value chain', 'Community', 'Regenerative materials depend on aligned growers, makers, and brands.', 'The transition to lower-impact materials is a collective project. Connecting growers, converters, researchers, and brands creates the practical feedback loops needed to scale responsibly.', 'assets/images/blog-a-vivid-vibrant-green-young-plant-3.jpg', 'CassavaForge', 3, 1),
(UUID(), 'a-materials-update', 'A materials update from CassavaForge', 'Product Update', 'New formulations and pilot conversations are moving from the lab toward real applications.', 'Our current focus is translating promising cassava resin blends into dependable solutions for packaging, films, and molded products. We are testing the variables that matter in real manufacturing environments.', 'assets/images/blog-close-up-macro-studio-photography-of-1.jpg', 'CassavaForge', 3, 1);
