import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "primary-container": "#15803d",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#005323",
        "secondary-container": "#6bff8f",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#4ae176",
        "on-surface": "#1b1b1e",
        "on-background": "#1b1b1e",
        "inverse-on-surface": "#f3f0f4",
        "primary-fixed-dim": "#79db8d",
        "on-surface-variant": "#3f493f",
        "inverse-surface": "#303033",
        primary: "#00652c",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f6f2f7",
        background: "#fbf8fc",
        outline: "#6f7a6e",
        "tertiary-fixed": "#b1f2be",
        "surface-bright": "#fbf8fc",
        "on-secondary-container": "#007432",
        tertiary: "#25623a",
        "on-tertiary-fixed-variant": "#12512c",
        "primary-fixed": "#95f8a7",
        surface: "#fbf8fc",
        "inverse-primary": "#79db8d",
        "surface-container-highest": "#e4e1e6",
        "on-primary-container": "#d3ffd5",
        "secondary-fixed": "#6bff8f",
        secondary: "#006e2f",
        "on-tertiary-fixed": "#00210d",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0edf1",
        "outline-variant": "#becabc",
        "tertiary-container": "#3f7b51",
        "on-secondary-fixed-variant": "#005321",
        "on-tertiary-container": "#d0ffd7",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#96d5a3",
        "surface-variant": "#e4e1e6",
        "surface-dim": "#dcd9dd",
        "surface-tint": "#006d30",
        "on-primary-fixed": "#00210a",
        "on-secondary-fixed": "#002109",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae7eb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-3xl": "4.5rem",
        "space-4xl": "6rem",
        "layout-margin-mobile": "1rem",
        "space-md": "1rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "layout-gutter": "1.5rem",
        "space-sm": "0.75rem",
        "space-2xs": "0.25rem",
        "layout-margin-desktop": "3rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "label-md": ["Manrope"],
        "headline-xl-mobile": ["Manrope"],
        "display-hero-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "label-caps": ["Manrope"],
        "display-hero": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-sm": ["Manrope"],
        "body-sm": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-xl": ["Manrope"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
